
def build(bld):
    bld.DefineGem(
        pch                     = "",
        disable_pch             = True,
        file_list               = ['tracyprofiler.waf_files'],

        includes        = [bld.Path('Code/CryEngine/CryCommon')],
        export_includes = [bld.Path('Gems/TraceyProfiler/External/Include')],

        # TRACY_ENABLED turns the tracy profiler on
        debug_defines = ['TRACY_ENABLED'],
        profile_defines = ['TRACY_ENABLED'],
        performance_defines = ['TRACY_ENABLED'],

        # AZ_PROFILE_TELEMETRY turns on profiling telemetry in the engine
        debug_export_defines = ['AZ_PROFILE_TELEMETRY'],
        profile_export_defines =['AZ_PROFILE_TELEMETRY'],
        performance_export_defines =['AZ_PROFILE_TELEMETRY']
    )
