
def build(bld):
    bld.DefineGem(
        pch                     = "",
        disable_pch             = True,
        file_list               = ['tracyprofiler.waf_files'],
        use_lib                 = ['TRACY_PROFILER'],
        includes                = [bld.Path('Code/CryEngine/CryCommon')],
        export_internal_3rd_party_libs = True,
        export_includes         = [ bld.Path('Gems/TracyProfiler/External') ],
        #export_system_includes = [],

        # TRACY_ENABLE turns the tracy profiler on in Tracy.cpp
        debug_defines = ['TRACY_ENABLE'],
        profile_defines = ['TRACY_ENABLE'],
        performance_defines = ['TRACY_ENABLE'],

        # TRACY_ENABLE turns the tracy profiler on in AzCore
        debug_export_defines = ['TRACY_ENABLE'],
        profile_export_defines =['TRACY_ENABLE'],
        performance_export_defines =['TRACY_ENABLE']

        #platform_roots = [bld.PlatformRoot('Source/Platform', export_includes=False)]
    )
